### PR TITLE
Prevent page refresh on enter, fixes #5

### LINKED ISSUE #5: pressing enter on an inputfield refreshes the page
This is  a **bug**.

### Prerequisites
Yes

### Description

pressing enter while focussed on an InputField generated by an `<enso-form>` (unmodified stub code) causes a GET-request to the same url (with empty query param, i.e. `?` appended)

No log output or events exposed to indicate the potential source

### Steps to Reproduce
1. open an enso form
2. press enter after focussed on/updating an input

### Expected behavior

Form to save.

### Actual behavior

page refresh, data lost.

### PR DESCRIPTION
**Pull request by jlsjonas**

### CODE REVIEW

**Comment by aocneanu** [comment]
this also fixes clicking on disabled buttons (worked before)

File: src/bulma/parts/FormContent.vue [hunk 1]
```diff
@@ -1,7 +1,7 @@
 <template>
     <div>
         <form-header/>
-        <form class="is-marginless">
+        <form class="is-marginless" @submit.prevent="">
```
Comment (aocneanu) [inline src/bulma/parts/FormContent.vue]: do we need the `""`

Comment (jlsjonas) [reply src/bulma/parts/FormContent.vue]: I thought we did, but looks like we don't after all.
